{
 "title": "РАБОТА",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "ТЕМПЕРАТУРЫ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "drum",
     "tags": { "item_id": "*" }
    }
   ]
  },
  {
   "title": "ФИЛЬТР",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "filter",
     "tags": { "item_id": "*" }
    }
   ]
  },
  {
   "title": "МАССЫ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "weight.m",
     "tags": { "item_id": "*" }
    }
   ]
  },
  {
   "title": "ПРИЕМНЫЙ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "weight.eu",
     "tags": { "item_id": "*" }
    }
   ]
  }
 ]
}